### ISSUE TITLE
📌 Meta: Tracking comparisons to other projects

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [bingo-js/bingo#20]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

The need for composable, reusable repository templates has had a lot of solution attempts over the years. I'd like to make sure each of them is documented in create's docs. These explanations should include:

* An overview of the other project
* What it brings
* How create differs from it

I included a lot of comparisons in the FAQs prior to this issue. They're all sub-headings within **https://www.create.bingo/faqs/#comparisons-table**. But I didn't get all projects, and keep learning about new ones!

Long task list to make sure none are forgotten:

- [ ] [@pnpm/meta-updater](https://github.com/pnpm/meta-updater): I'll file an issue soon, courtesy of https://bsky.app/profile/kochan.io/post/3lcbofppufk23
- [ ] Ansible: _todo_
- [ ] Chef: _todo_
- [x] [create-next-app](https://nextjs.org/docs/app/api-reference/cli/create-next-app): _(prior to this issue)_
- [x] [create-react-app](https://create-react-app.dev): _(prior to this issue)_
- [x] [create-typescript-app](https://github.com/JoshuaKGoldberg/create-typescript-app): _(prior to this issue)_
- [x] [Cookiecutter](https://github.com/cookiecutter/cookiecutter): _(prior to this issue)_
- [x] [copier](https://copier.readthedocs.io/en/latest): _(prior to this issue)_
- [x] [degit](https://github.com/Rich-Harris/degit): _(prior to this issue)_
- [x] [GitHub Template Repositories](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository): _(prior to this issue)_
- [x] [Hygen](https://www.hygen.io): _(prior to this issue)_
- [ ] Kubernetes: _todo_
- [x] [Plop](https://github.com/plopjs/plop): _(prior to this issue)_
- [x] [projen](https://projen.io): _(prior to this issue)_
- [ ] [update](https://www.npmjs.com/package/update): I'll file an issue soon, courtesy of https://bsky.app/profile/kochan.io/post/3lcbofppufk23
- [x] [Yeoman](https://yeoman.io): _(prior to this issue)_

If anybody knows of any other engines/frameworks that belong on that list, please do post them! I'd be happy to take a look and post a comparison.

The only exception would be other dedicated `create-*-app` projects. They're all lumped together in one section: https://www.create.bingo/faqs/#create-next-app-create-react-app-create-typescript-app-etc.

### Additional Info

Note that none of this should be phrased combatively or competitively. A healthy ecosystem should have multiple different attempts to solve common issues. That's how we learn and grow! 

Also, a lot of these projects are not trying to solve the same problems as create. I've just been asked how the compare and contrast before.

💖

**Comment by tommy-mitchell** [comment]
I'm currently using [`tmplr`](https://github.com/loreanvictor/tmplr) for my project templates. Another I had looked at is adapting [`pupa`](https://github.com/sindresorhus/pupa) for component templating, before I found Plop.

---

Also - may want to update the links in the issue description to use [create.bingo](https://www.create.bingo) :)

**Comment by JoshuaKGoldberg** [comment]
Awesome, thanks! Filed #217 to get to them.
